### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [zakir2k/date-a-scientist#2]
### Criteria 1: Valid Python Code
* _Score Level:_ 2 (Approaches expectations) 
* _Comment(s):_ Your code runs with errors, e.g., `ValueError: Input contains NaN, infinity or a value too large for dtype('float64')` after running:

```
regressor = KNeighborsRegressor(n_neighbors=5,weights="distance")
regressor.fit(train,df.height)
print(regressor.predict([25,36]))
```
Also in general, you should make sure you don't call variables before you define them. I'm able to run your code if I 'Run all' in Jupyter notebooks, but not when I run the cells individually in order.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ Like I mentioned in issue #1, you should remove outliers when you're exploring your data so they don't obscure any possible trends or relationships. Also, your data exploration should ideally inform your research questions -- what made you decide to look into drug users/drinkers and body types? In general, your data is explored too briefly, and the experimental questions chosen are only barely related data exploration.
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your algorithms are used correctly and the correct conclusions are drawn from the results.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 2 (Approaches expectations)
* _Comment(s):_ You state your research questions, but it's not clear what you mean in your first question. That is, what do you mean by "better" body types, and why would you predict that drug use/drinking would lead users to use "better" body type classification? Your third question is confusing as well, are you trying to predict these users heights 20 years from now, and if so, why would you expect them to change significantly? You do a good job including information about model run time, complexity, etc., but it would be better to have a little more discussion about what your results mean and how your arrived at your conclusions

### Criteria 5: Code formatting
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Your code is formatted nicely, but see my note in Criteria 1 about calling variables before you define them.

**Comment by zakir2k** [comment]
Much appreciated! Good feedback and I hope to take this further in my learning.
